---
- name: Create Directory
  hosts: localhost
  gather_facts: no

  vars:
    new_path: "{{ var_newdir }}"

  tasks:
   - name: Create Directory
     ansible.builtin.file:
       path: "{{ new_path }}"
       mode: "0755"
       state: directory
