---
- name: Create Directory
  hosts: localhost
  vars:
    new_path: "{{ var_newdir }}"

  tasks:
   - name: Create Directory
     file:
       path: "{{ new_path }}"
       mode: "0755"
       state: directory

