---
- name: Upgrade junos
  hosts: all
  collections:
    - juniper.device
  connection: local
  serial: 1
  gather_facts: no

  vars:
    port: 22
    wait_time: 3600
    pkg_dir: "{{ var_dir }}"
    OS_package: "{{ var_package }}"

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: host={{ ansible_ssh_host }} port=22 timeout={{ wait_time }}

    - name: Install Junos OS package
      software:
        local_package: "{{ pkg_dir }}/{{ OS_package }}"
        validate: true
        checksum_timeout: 420
        cleanfs_timeout: 600
        install_timeout: 2000
        reboot_pause: 120
        checksum_algorithm: md5
        logdir: "{{ var_dir}}/logs"
        level: "INFO"
      register: upgrade_response
      notify:
        - wait_reboot

    - name: Print response
      debug:
        var: upgrade_response

  handlers:
    - name: wait_reboot
      wait_for: host={{ ansible_ssh_host }} port=22 timeout={{ wait_time }}
      when: not upgrade_response.check_mode
