---
- name: Investigate file access
  hosts: localhost
  gather_facts: no
  vars:
    path: "/mnt/awx/data"
  tasks:
    - name: Get mount info
      command: mount
      register: mount_info

    - name: Show mount info
      debug:
        msg: "{{ mount_info.stdout_lines | select('search', '/mnt/awx/data') | list }}"

    - name: Get directory info with ls
      command: ls -la /mnt/awx/data
      register: ls_output

    - name: Show ls output
      debug:
        var: ls_output.stdout_lines

    - name: Get directory owner details
      command: stat /mnt/awx/data
      register: stat_output

    - name: Show stat output
      debug:
        var: stat_output.stdout_lines

    - name: Test file creation
      copy:
        content: "test content"
        dest: "{{ path }}/test_from_ee.txt"
      register: file_creation
      ignore_errors: yes

    - name: Show file creation result
      debug:
        var: file_creation