---
- name: Print all files in the directory
  hosts: localhost
  gather_facts: no
  vars:
    path: "/mnt/awx/data"
  tasks:
    - name: Get current user info
      command: id
      register: user_info
      
    - name: Debug user info
      debug:
        var: user_info.stdout

    - name: Check directory permissions
      command: ls -la "{{ path }}"
      register: ls_output
      ignore_errors: yes

    - name: Debug directory permissions
      debug:
        var: ls_output

    - name: Find all files
      find:
        paths: "{{ path }}"
        recurse: no
        file_type: file
      register: found_files

    - name: Show found files
      debug:
        var: found_files