---
- name: Print all files in the directory
  hosts: localhost
  gather_facts: no
  vars:
    path: "/mnt/awx/data"
  tasks:
    - name: Get current user info
      command: id
      register: user_info
      
    - name: Debug user info
      debug:
        var: user_info.stdout

    - name: Check directory existence with ls
      command: ls -la "{{ path }}"
      register: ls_output
      ignore_errors: yes

    - name: Debug ls output
      debug:
        var: ls_output

    - name: Ensure directory exists
      file:
        path: "{{ path }}"
        state: directory
        mode: '0755'
        owner: awx
        group: root
      become: yes
      
    - name: Find all files
      find:
        paths: "{{ path }}"
        recurse: no
        file_type: file
      register: found_files

    - name: Show found files
      debug:
        var: found_files