---
- name: Fetch Juniper inventory from Netbox and save as static inventory
  hosts: localhost
  gather_facts: false
  
  vars:
    netbox_url: "http://192.168.1.102:8000"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    inventory_file: "juniper_inventory.yml"
    output_dir: "{{ playbook_dir }}/inventories"
  
  tasks:
    - name: Create inventory directory
      file:
        path: "{{ output_dir }}"
        state: directory
        mode: '0755'
      
    - name: Fetch Juniper devices from Netbox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?status=active&manufacturer=juniper"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: "application/json"
        validate_certs: no
        return_content: yes
      register: netbox_devices
      
    - name: Debug received data
      debug:
        msg: "Received {{ netbox_devices.json.results | length }} devices from Netbox"
      when: netbox_devices.json is defined

    - name: Process devices by role
      set_fact:
        routers: "{{ netbox_devices.json.results | selectattr('role.name', 'equalto', 'Juniper Router') | list }}"
        switches: "{{ netbox_devices.json.results | selectattr('role.name', 'equalto', 'Juniper Switch') | list }}"

    - name: Create router hosts dictionary
      set_fact:
        router_hosts: "{{ dict(routers | map(attribute='name') | map('regex_replace', '^(.*)$', '\\1={}') | map('split', '=')) }}"

    - name: Create switch hosts dictionary
      set_fact:
        switch_hosts: "{{ dict(switches | map(attribute='name') | map('regex_replace', '^(.*)$', '\\1={}') | map('split', '=')) }}"

    - name: Create host vars
      set_fact:
        host_vars: "{{ {} }}"

    - name: Populate host vars
      set_fact:
        host_vars: "{{ host_vars | combine({ item.name: {
          'ansible_host': item.primary_ip4.address | regex_replace('/.*$', ''),
          'device_type': item.device_type.model,
          'site': item.site.name,
          'role': item.role.name,
          'tags': item.tags | map(attribute='name') | list,
          'tenant': item.tenant.name | default(''),
          'rack': item.rack.name | default(''),
          'location': item.location.name | default('')
        }}) }}"
      loop: "{{ netbox_devices.json.results }}"

    - name: Create final inventory structure
      set_fact:
        inventory_data:
          all:
            children:
              juniper:
                children:
                  juniper_routers:
                    hosts: "{{ router_hosts }}"
                  juniper_switches:
                    hosts: "{{ switch_hosts }}"
          _meta:
            hostvars: "{{ host_vars }}"

    - name: Save inventory to YAML file
      copy:
        content: "{{ inventory_data | to_nice_yaml }}"
        dest: "{{ output_dir }}/{{ inventory_file }}"
        mode: '0644'
      
    - name: Display inventory file location
      debug:
        msg: 
          - "Inventory file created at: {{ output_dir }}/{{ inventory_file }}"
          - "Number of routers: {{ routers | length }}"
          - "Number of switches: {{ switches | length }}"