---
- name: check netconf connection
  hosts: all
  collections:
    - juniper.device
  connection: local
  gather_facts: no
  vars:
    netconf_port: "{{ var_netconf_port }}"
    wait_time: 30

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: host={{ ansible_ssh_host }} port={{ netconf_port }} timeout={{ wait_time }}
