---
- name: Junos Gather facts
  hosts: vSRX
  gather_facts: no

  collections:
    - junipernetworks.junos

  vars:
    ansible_connection: netconf
    ansible_network_os: junos

  tasks:
    - name: Time Zone
      junipernetworks.junos.junos_config:
        lines:
          - set system time-zone Europe/Madrid
      tags: ntp

    - name: TEST 2 - Execute three commands.
      junipernetworks.junos.junos_command:
        commands:
          - "show version"
          - "show system uptime"
          - "show interfaces terse"
      register: test2
      tags: commands

    - name: gather juniper junos facts
      junipernetworks.junos.junos_facts:
        gather_network_resources: "{{ network_resource | default('!vlans,!bgp_global,!bgp_address_family,!ospf_interfaces') }}"
      tags: resources