---
- name: Gather user information
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: TEST1 - Gather user information
      junos_command:
        commands:
          - show system users
        provider: "{{ credential }}"
      register: result

    - name: Check TEST 1
      ansible.builtin.assert:
        that:
          test1.msg == "The command executed successfully."

    - name: Creates directory
      ansible.builtin.file:
        path: out
        state: directory
        mode: '0644'

  - debug: var=result.stdout

