---
- name: ping host
  hosts: all
  connection: local
  gather_facts: no
  vars:
    ping_failed: []

  tasks:
    - name: ping
      ping:
      register: ping_result
      retries: 1
      delay: 1
      ignore_errors: no
    
    - name: Collect results
      set_fact:
        ping_failed: "{{ ping_failed + [inventory_hostname] }}"
      when: ping_result is failed

    - name: Fail the playbook if any ping fails after retries
      fail:
        msg: "Failed to reach: {{ ping_failed }}"
      when: ping_failed | length > 0
