---
- name: Test file access with detailed error reporting
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Debug mount points
      shell: "mount | grep '/mnt/awx/data'"
      register: mount_output
      ignore_errors: yes

    - name: Show mount info
      debug:
        var: mount_output

    - name: Debug directory permissions
      shell: "ls -ld /mnt/awx/data 2>&1 || true"
      register: dir_perms
      ignore_errors: yes

    - name: Show directory permissions
      debug:
        var: dir_perms

    - name: Try to list files
      shell: "ls -la /mnt/awx/data 2>&1 || true"
      register: ls_output
      ignore_errors: yes

    - name: Show ls output
      debug:
        var: ls_output